<a href="https://colab.research.google.com/github/rivaldo125/rivaldopatriakusuma/blob/main/UAS_NO2b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Dataset
body =['Cold','Cold', 'Warm', 'Warm', 'Warm']
gives =['No', 'Yes', 'No','No','No']
fourlegged =['Yes',  'No', 'No', 'No','Yes']
hibernate =['Yes',  'No', 'No', 'Yes','Yes']

mamalia =['No', 'No','No','No', 'Yes']

In [2]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
#Convert label string ke numbers
body_encoded=le.fit_transform(body)
print (body_encoded)

[0 0 1 1 1]


In [3]:
#Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
label = preprocessing.LabelEncoder()
#Convert label string ke numbers
gives_encoded=label.fit_transform(gives)
print (gives_encoded) 

fourlegged_encoded=label.fit_transform(fourlegged)
print (fourlegged_encoded)

hibernate_encoded=label.fit_transform(hibernate)
print (hibernate_encoded)

mamalia_encoded=label.fit_transform(mamalia)
print (mamalia_encoded)

[0 1 0 0 0]
[1 0 0 0 1]
[1 0 0 1 1]
[0 0 0 0 1]


In [4]:
print ("body            :",body_encoded)
print ("gives           :",gives_encoded)
print ("fourlegged      :",fourlegged_encoded)
print ("hibernate       :",hibernate_encoded)
print ("mamalia         :",mamalia_encoded)

body            : [0 0 1 1 1]
gives           : [0 1 0 0 0]
fourlegged      : [1 0 0 0 1]
hibernate       : [1 0 0 1 1]
mamalia         : [0 0 0 0 1]


In [5]:
#Combining fitur-fitur yang ada
features=zip(body_encoded,gives_encoded,fourlegged_encoded,hibernate_encoded)
features=list(features)
print (tuple(features))

((0, 0, 1, 1), (0, 1, 0, 0), (1, 0, 0, 0), (1, 0, 0, 1), (1, 0, 1, 1))


In [6]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Panggil Gaussian Classifier
model = GaussianNB()

#Train model untuk data training
model.fit(features,mamalia)
#Model.fit(features,label.reshape(-1,1))

#Peridiction Output
predicted = model.predict([[1,1,0,0]]) #1 : warm, 1: Yes, 0: No , 0 : No
print ("Hasil Perdiksi:", predicted)

Hasil Perdiksi: ['No']
